DOMAIN = "copilot_bridge"
DEFAULT_URL = "http://127.0.0.1:8099"
SERVICE_ASK = "ask"
SERVICE_GET_GITHUB_AUTH_STATUS = "get_github_auth_status"
SERVICE_START_GITHUB_DEVICE_FLOW = "start_github_device_flow"
SERVICE_POLL_GITHUB_DEVICE_FLOW = "poll_github_device_flow"
SERVICE_SET_GITHUB_TOKEN = "set_github_token"
SERVICE_CLEAR_GITHUB_AUTH = "clear_github_auth"
DATA_CLIENT = "client"
DATA_AGENT = "agent"
CONF_USE_HOME_ASSISTANT_MCP = "use_home_assistant_mcp"
CONF_HOME_ASSISTANT_MCP_SERVER_NAME = "home_assistant_mcp_server_name"
DEFAULT_HOME_ASSISTANT_MCP_SERVER_NAME = "home_assistant"

